name: atomsbox_simple_news_app_server_with_dart_frog
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.4

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  flutter_lints: ^2.0.1