part of 'in_memory_news_data_source.dart';

final List<Article> articles = [
  Article(
    id: '1',
    author: const Author(id: '1', name: 'Massimo', surname: 'D.'),
    headline: 'This is a short headline',
    leadParagraph:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
    supportingParagraph: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
    ],
    imageUrl:
        'https://images.unsplash.com/photo-1523292562811-8fa7962a78c8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80',
    createdAt: DateTime.now(),
    modifiedAt: DateTime.now(),
    isBreakingNews: true,
    isPopular: true,
    category: NewsCategory.politics,
  ),
  Article(
    id: '2',
    author: const Author(id: '1', name: 'Massimo', surname: 'D.'),
    headline: 'This is a short headline',
    leadParagraph:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
    supportingParagraph: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
    ],
    imageUrl:
        'https://images.unsplash.com/photo-1678005102553-8d583f536691?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2670&q=80',
    createdAt: DateTime.now(),
    modifiedAt: DateTime.now(),
    isBreakingNews: true,
    isPopular: true,
    category: NewsCategory.economy,
  ),
  Article(
    id: '3',
    author: const Author(id: '1', name: 'Massimo', surname: 'D.'),
    headline: 'This is a short headline',
    leadParagraph:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
    supportingParagraph: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
    ],
    imageUrl:
        'https://images.unsplash.com/photo-1523995462485-3d171b5c8fa9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80',
    createdAt: DateTime.now(),
    modifiedAt: DateTime.now(),
    isBreakingNews: true,
    isPopular: true,
    category: NewsCategory.politics,
  ),
  Article(
    id: '4',
    author: const Author(id: '1', name: 'Massimo', surname: 'D.'),
    headline: 'This is a short headline',
    leadParagraph:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
    supportingParagraph: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
    ],
    imageUrl:
        'https://images.unsplash.com/photo-1678005102553-8d583f536691?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2670&q=80',
    createdAt: DateTime.now(),
    modifiedAt: DateTime.now(),
    isBreakingNews: false,
    isPopular: true,
    category: NewsCategory.economy,
  ),
  Article(
    id: '5',
    author: const Author(id: '1', name: 'Massimo', surname: 'D.'),
    headline: 'This is a short headline',
    leadParagraph:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
    supportingParagraph: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
    ],
    imageUrl:
        'https://images.unsplash.com/photo-1555848962-6e79363ec58f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1733&q=80',
    createdAt: DateTime.now(),
    modifiedAt: DateTime.now(),
    isBreakingNews: false,
    isPopular: true,
    category: NewsCategory.politics,
  ),
  Article(
    id: '6',
    author: const Author(id: '1', name: 'Massimo', surname: 'D.'),
    headline: 'This is a short headline',
    leadParagraph:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
    supportingParagraph: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut mauris leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque sed quam eu nibh posuere scelerisque non at ligula. Cras blandit.',
    ],
    imageUrl:
        'https://images.unsplash.com/photo-1678005102553-8d583f536691?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2670&q=80',
    createdAt: DateTime.now(),
    modifiedAt: DateTime.now(),
    isBreakingNews: false,
    isPopular: true,
    category: NewsCategory.economy,
  )
];
